remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: spamfilter
description: Streamlined, object-oriented and fully customizable python spam mitigation library.
show_downloads: true